### ISSUE TITLE
Picklist import error

### ISSUE THREAD

**Issue by Tronko86** [microsoft/process-migrator#102]
the problem still occurs

`
Call stack:Error: You must provide a value for the Items parameter.
    at RestClient.<anonymous> (..\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (..\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] [2024-05-16T21:08:15.023Z] Import failed, see log file for details. Failed to create picklist for field Custom.ImpattineiProcessi, see logs for details.
`

`
{
  "referenceName": "Custom.ImpattineiProcessi",
  "name": "Impatti nei Processi",
  "type": 1,
  "pickList": {
    "id": "xxxx",
    "name": "picklist_8aefa033-e26e-41db-94d4-370bb3990c50",
    "type": "String",
    "isSuggested": true,
    "url": "https://xxxxxxxx.visualstudio.com/_apis/work/processDefinitions/lists/15fa5a9e-82e2-4a28-ba98-788de8dc84d9"
  },
  "readOnly": false,
  "required": false,
  "defaultValue": null,
  "url": "https://xxxxxxxx.visualstudio.com/_apis/work/processDefinitions/c710705b-e398-4cbc-bf23-af1a9795c364/workItemTypes/NPF-Workflow.Feature/fields/Custom.ImpattineiProcessi",
  "allowGroups": null
},
`
#11

**Comment by AminTi** [comment]
Thanks for reporting this. We have already added it to the backlog.

**Comment by jenny-curry** [comment]
What caused this for me was that I had a picklist defined that had an empty array of picklist items defined in the items property. I grabbed an option defintion from another picklist in my process.json file, and I was able to get past this error.
Example Solution in your process.json file:
"witFieldPicklists": 
{
  {
      "workitemtypeRefName": "{Ref Name}",
      "fieldRefName": "{Field Ref Name}",
      "picklist": {
         // items is no longer an empty array
        "items": [
          {
            "id": "{Item ID}", 
            "value": "Other"
          }
        ],
        "id": "{GUID}",
        "name": "picklist_{GUID}",
        "type": "String",
        "isSuggested": true,
        "url": "https://dev.azure.com/{Org Name}/_apis/work/processDefinitions/lists/{GUID}"
      }
    },
}
