### ISSUE TITLE
We are getting errors with Group names while we migrate Inherited process to a vanilla VSTS account 

### ISSUE THREAD

**Issue by rakeshkasoju** [Microsoft/process-migrator#12]
Hi,

We have applied customization's on an Inherited process(VSTS) and trying to migrate this inherited process to a vanilla VSTS account, but we are getting below issue with process-migrator

Exception message:VS403113: A group with label 'General' already exists in page 'Details'.
Call stack:Error: VS403113: A group with label 'General' already exists in page 'Details'.
    at RestClient.<anonymous> (C:\Users\v-karake\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:173:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\v-karake\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:6:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[ERROR] [2018-06-27T11:14:22.814Z] Import failed, see log file for details. Failed to create group 'ad017ec5-4ac4-4f13-873e-634cdbf09988' in page 'CMMI.Task.Task', see logs for details.

Ideally we want the Group name as "General" and after fixing this, we are getting same set of errors for other WIT's as well. 

So can you please suggest any work around and next step to proceed further and it's blocking us 

Thanks in advance

Regards,
Rakesh

**Comment by rakeshkasoju** [comment]
This is has been fixed now

Observed that System Default Groups can't be moved to other place, so have renamed it and created a new group with the original name, hence we were getting these errors.

Now these have been fixed

Thanks
