### ISSUE TITLE
Cannot find module 'guid-typescript' on running process-migrator command

### ISSUE THREAD

**Issue by RensBonnez** [microsoft/process-migrator#27]
After installation I get following error when running the 'process-migrator' command:

module.js:550
    throw err;
    ^

Error: Cannot find module 'guid-typescript'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/process-migrator/build/nodejs/common/Utilities.js:10:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`

If I check the node-modules that are coming with the process-migrator package and the 'guid-typescript' is there.

Tried both with node 8.12.0 and with 8.9.4.

**Comment by liang2zhu1** [comment]
@RensBonnez could you share which OS and version you are on? also does that happen with 10.x node.js?
