### ISSUE TITLE
cryptic error if missing sufficient permissions to export

### ISSUE THREAD

**Issue by seanknox** [microsoft/process-migrator#28]
I'm trying to generate a source account token with minimal permissions needed for exporting. When permissions are insufficient, I get an `ECONNRESET` error from the API:

```
INFORMATION] [2018-11-19T21:55:49.985Z] Full log is sent to '/Users/seanknox/src/microsoft/process-migrator/output\processMigrator.log'
[VERBOSE] [2018-11-19T21:55:49.992Z] Keyboard listener added
[VERBOSE] [2018-11-19T21:55:49.992Z] Begin step 'Get rest client on source account 'https://myorgname.visualstudio.com/''.
[VERBOSE] [2018-11-19T21:55:50.514Z] Finished step 'Get rest client on source account 'https://myorgname.visualstudio.com/''.
[INFORMATION] [2018-11-19T21:55:50.515Z] Export process started.
[VERBOSE] [2018-11-19T21:55:50.515Z] Begin step 'Get source process Id from name'.
[VERBOSE] [2018-11-19T21:55:50.845Z] Finished step 'Get source process Id from name'.
[VERBOSE] [2018-11-19T21:55:50.846Z] Begin step 'Get artifacts from source process'.
[VERBOSE] [2018-11-19T21:55:53.586Z] Exception message:read ECONNRESET
Call stack:Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TLSWrap.onread (net.js:619:25)
[ERROR] [2018-11-19T21:55:53.586Z] Encountered unkonwn error, check log file for details.
```

**Comment by liang2zhu1** [comment]
@seanknox  thanks reporting this - could you share the Node.js version?

**Comment by henryrt** [comment]
I'm trying to create the PAT in AzDevops and would also like to minimize the scopes granted. What is the minimal set of scopes needed?

**Comment by liang2zhu1** [comment]
The scope should be FULL for work item 
![image](https://user-images.githubusercontent.com/4074892/61010120-e3a8fc00-a329-11e9-9041-973019c5c78b.png)
