### ISSUE TITLE
Error while running process-Migrator

### ISSUE THREAD

**Issue by mishra1010** [Microsoft/process-migrator#7]
C:\Users\xxxx\AppData\Roaming\npm>process-Migrator --config "C:\Users\xxxx\Desktop\configuration.json"
C:\Users\xxxx\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\main.js:16
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

npm version is 6.1
Please help in fixing this issue

**Comment by alexcnichols** [comment]
PS C:\users\xxxx\tools> process-migrator
C:\Users\xxxx\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\main.js:16
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

Same error here just running without params.
process-migrator@0.9.4
npm: '6.1.0'

**Comment by liang2zhu1** [comment]
What is your Node.Js version? @alexcnichols @mishra1010  , are you on LTS 8.11.x?

**Comment by mishra1010** [comment]
It's v6.10.3

**Comment by liang2zhu1** [comment]
@mishra1010  Thanks for the information, then it's kind of expected because of using native promise it requires LTS Node.Js - you can try build it with tsconfig.json setting below but I did not test with that
`"target": "es2017"`

**Comment by alexcnichols** [comment]
Upgraded Node.JS to LTS v8.11.3 and re-ran. Looks better.

PS C:\Users\xxxx> node --version
v6.11.1
PS C:\Users\xxxx> node --version
v8.11.3
PS C:\Users\xxxx\Tools> process-migrator
[ERROR] [2018-06-20T04:35:52.292Z] Cannot find configuration file 'configuration.json'
[INFORMATION] [2018-06-20T04:35:52.298Z] Generated configuration file as 'configuration.json', please fill in required information and retry.

**Comment by liang2zhu1** [comment]
Thanks Alex - I consider this closed now.
