### ISSUE TITLE
Agile BUG two System info groups - import issue

### ISSUE THREAD

**Issue by LukasKu** [microsoft/process-migrator#73]
Hello,
I have tried to migrate process, but an error occured. 

[VERBOSE] [2022-10-07T07:54:07.263Z] Exception message:VS403113: A group with label 'System Info' already exists in page 'Details'.
Call stack:Error: VS403113: A group with label 'System Info' already exists in page 'Details'.
    at RestClient.<anonymous> (C:\Users\lukkuj\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\lukkuj\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[ERROR] [2022-10-07T07:54:07.264Z] Import failed, see log file for details. Failed to edit group 'Agile.Bug.Bug.System Info.WideGroup' in page 'Agile.Bug.Bug', see logs for details.

We do not have modified BUG, there are in the parent process two groups with same name.

**Comment by montant** [comment]
Any update on this issue? I'm facing it today too.

**Comment by KreoCZ** [comment]
Hello, we encountered a same problem today while importing an exported process. We are looking for any assistance or solutions to resolve this issue.  Any idea?  Thank you.

**Comment by LukasKu** [comment]
> Hello, we encountered a same problem today while importing an exported process. We are looking for any assistance or solutions to resolve this issue. Any idea? Thank you.

Hello, try to rename standard field group on a BUG. There are two groups with name System info and it cause issue. I have renamed them and an issue gone

**Comment by KreoCZ** [comment]
> > Hello, we encountered a same problem today while importing an exported process. We are looking for any assistance or solutions to resolve this issue. Any idea? Thank you.
> 
> Hello, try to rename standard field group on a BUG. There are two groups with name System info and it cause issue. I have renamed them at source DevOps and an issue gone

Thanks for your proposal. I fixed my issue by switching  "overridden": true, from below code:

`"id": "Agile.Bug.Bug.System Info.WideGroup",
                    "inherited": true,
                    "overridden": true,`

to false:

`"id": "Agile.Bug.Bug.System Info.WideGroup",
                    "inherited": true,
                    "overridden": false`

This field has been marked as overridden because in source process we hidden this field. I found usefull info in already closed issue - [link](https://github.com/microsoft/process-migrator/issues/24)
