### ISSUE TITLE
Custom Completed State Category - Fails during migration/import

### ISSUE THREAD

**Issue by christian-skj** [microsoft/process-migrator#83]
We have created a custom value for the 'Completed' State Category. This fails with the following error message when running the process-migrator:

```
[VERBOSE] [2023-07-14T07:58:42.397Z] Exception message:VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
Call stack:Error: VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
    at RestClient.<anonymous> (C:\Users\Test\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Test\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] [2023-07-14T07:58:42.398Z] Import failed, see log file for details. Unable to create/hide/update state 'Approved' in 'business_layer.Milestone' work item type, see logs for details
```

**Comment by AminTi** [comment]
Hi, thanks for reporting I  will try to reproduce it and get back to you.

**Comment by Awnhumbla** [comment]
Hi 
Any progress on this issue? We are experiencing the same error:

[VERBOSE] [2023-11-07T15:18:05.705Z] Exception message:VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
Call stack:Error: VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
    at RestClient.<anonymous> (C:\Users\xxx\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xxx\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] [2023-11-07T15:18:05.706Z] Import failed, see log file for details. Unable to create/hide/update state 'Done' in 'SCALESDevOpsScrum-Copy.TestCase' work item type, see logs for details

**Comment by wickens** [comment]
I am also getting this. It seems the only workaround is to remove custom completed states from all backlog item types. Are there any better workarounds?

**Comment by testingLuciano** [comment]
Same thing to me
