### ISSUE TITLE
userSpecifiedMode.toLocaleLowerCase is not a function error

### ISSUE THREAD

**Issue by tkostis** [microsoft/process-migrator#90]
Using the latest versions of nodejs/npm/process-migrator, when attempting to import a custom process template we receive the below error when attempting to use the '-mode=' parameter with a properly formatted configuration.json
For example.  process-migrator -mode=import --config='c:\temp\configuration.json'

When we use the process-migrator command without the '-mode=' parameter (which would default to migrate mode) and have a properly configured configuration.json we are able to successfully migrate a process from one devops org to another.
For example.  process-migrator --config='c:\temp\configuration.json'

there appears to be some issue with main.js and ConfigurationProcessor.js

**Error Below**

C:\Users\root\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\ConfigurationProcessor.js:31
        switch (userSpecifiedMode.toLocaleLowerCase()) {
                                  ^

TypeError: userSpecifiedMode.toLocaleLowerCase is not a function
    at Object.ProcesCommandLine (C:\Users\root\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\ConfigurationProcessor.js:31:35)
    at main (C:\Users\root\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\main.js:18:57)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\main.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.1.0
PS C:\Users\root>

**Comment by MOlausson** [comment]
@tkostis thanks for reporting, we'll take a look at this and get back.

**Comment by aherrick** [comment]
i'm also seeing this. is there a work around here?

**Comment by FH-Inway** [comment]
Also getting this issue.

```
PS C:\Temp\ado-process-migrator> process-migrator --mode export
C:\Users\florian.hopfner\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\ConfigurationProcessor.js:31
        switch (userSpecifiedMode.toLocaleLowerCase()) {
                                  ^

TypeError: userSpecifiedMode.toLocaleLowerCase is not a function
    at Object.ProcesCommandLine (C:\Users\florian.hopfner\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\ConfigurationProcessor.js:31:35)
    at main (C:\Users\florian.hopfner\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\Main.js:18:57)
    at Object.<anonymous> (C:\Users\florian.hopfner\AppData\Roaming\npm\node_modules\process-migrator\build\nodejs\nodejs\Main.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1760:14)
    at Object..js (node:internal/modules/cjs/loader:1892:10)
    at Module.load (node:internal/modules/cjs/loader:1480:32)
    at Module._load (node:internal/modules/cjs/loader:1299:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)

Node.js v25.2.1

PS C:\Temp\ado-process-migrator> npm list -g
C:\Users\florian.hopfner\AppData\Roaming\npm
+-- npm@11.4.2
`-- process-migrator@0.10.1
```
