### ISSUE TITLE
Migration fails trying to create the "Scan" page

### ISSUE THREAD

**Issue by thomasbragaloni** [microsoft/process-migrator#93]
importing a process fails with the following error:

VS403112: A page with label 'Scans' already exists in the layout.
    at RestClient.<anonymous> (C:\...npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\...\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I have migrated several processes in the past but recently am seeing the error above.

**Comment by AminTi** [comment]
Hi, I will do some tests and let you know the results.
