### ISSUE TITLE
VS403093: Team Services currently does not support changes to 'Completed' category. 

### ISSUE THREAD

**Issue by MicE44** [microsoft/process-migrator#94]
Hi Devs,

our business changed the Completed category. State closed to done and others.
Export works but during the import I got this error:

Exception message:VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
Call stack:Error: VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
    at RestClient.<anonymous> (C:\Users\Z003MU9D-A01\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Z003MU9D-A01\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] [2023-11-30T14:04:32.697Z] Import failed, see log file for details. Unable to create/hide/update state 'Closed' in 'DLProcess.TechnicalUserStory' work item type, see logs for details

I talked with Microsoft, but they cant help me, because not supported tool :-D.

I tried to changed the state back to closed, but I got the same error.
Do you know this issue?
Do you have a nice solution for me?

Thanks for your feedback.

**Comment by MicE44** [comment]
I found this case
https://github.com/microsoft/process-migrator/issues/83

Its closed, but not solved...
Iam on the latest version  10.2.5.
But got the same error:
[ERROR] [2023-12-18T12:47:59.833Z] Import failed, see log file for details. Unable to create/hide/update state 'Verified' in 'DLProcess.TechnicalUserStory' work item type, see logs for details

**Comment by AminTi** [comment]
I'll perform a test and get back to you later.

**Comment by JAlexander22** [comment]
Hi, Currently getting the exact same error, do know the reason for this error?
